// CryptXiATL.idl : IDL source for CryptXiATL
//

// This file will be processed by the MIDL tool to
// produce the type library (CryptXiATL.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(1666aa0c-9d0e-4819-ad8c-98e7868dca47),
	dual,
	nonextensible,
	pointer_default(unique),
	custom(0F21F359-AB84-41E8-9A78-36D110E6D2F9, "Interop.CryptXi.IATLCryptXiObject")
]
interface IATLCryptXiObject : IDispatch
{
	[id(1), helpstring("Set key for encryption")] HRESULT SetKey([in] BSTR key, [out, retval] BSTR* result);
};
[
	uuid(134ebb80-1e1f-4efa-b1fc-67c95420c81e),
	version(1.0),
]
library CryptXiATLLib
{
	importlib("stdole2.tlb");
	[
		uuid(96c33d00-9fd3-446f-97fc-c58d2af9fda9),
		custom(0F21F359-AB84-41E8-9A78-36D110E6D2F9, "Interop.CryptXi.ATLCryptXiObject")
	]
	coclass ATLCryptXiObject
	{
		[default] interface IATLCryptXiObject;
	};
};

import "shobjidl.idl";
